{% set name = "ffpyplayer" %}
{% set version = "4.3.4" %}
{% set sha256 = "4889add255ded2b773731c858c1a8adb489a9223bacd0778062278de826b8af7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/matham/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  skip: true  # [py < 35]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pytest
    - cython
    - sdl2
    - sdl2_mixer
    - ffmpeg
    - libflac  # [win]
    - libvorbis  # [win]
    - pkg-config
    - msinttypes  # [win]
    - pulseaudio  # [linux]
    - alsa-lib  # [linux]
  run:
    - python
    - sdl2
    - sdl2_mixer
    - ffmpeg
    - libflac  # [win]
    - libvorbis  # [win]
    - pulseaudio  # [linux]
    - alsa-lib  # [linux]

test:
  imports:
    - ffpyplayer.player
  commands:
    - pytest ffpyplayer/tests
    - python -c "import ffpyplayer"
  requires:
    - pytest
  source_files:
    - examples
    - ffpyplayer/tests/test_pic.py
    - ffpyplayer/tests/test_write.py

about:
  home: https://github.com/matham/ffpyplayer
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: A cython implementation of ffmpeg based player, ffplay

  description: |
    FFPyPlayer is a python binding for the FFmpeg library for playing and writing
    media files.
  doc_url: http://matham.github.io/ffpyplayer/index.html
  dev_url: https://github.com/matham/ffpyplayer

extra:
  recipe-maintainers:
    - matham
