{% set name = "ffpyplayer" %}
{% set version = "4.1.0" %}
{% set sha256 = "1cd14cdf8299ddba4e41b1c28c90b777905b62ad512f8ad81f45b0c60bd4a6e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/matham/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [py < 27 or win and py < 35]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - nose
    - cython
    - sdl2
    - sdl2_mixer
    - ffmpeg
    - libflac  # [win]
    - libvorbis  # [win]
    - pkgconfig
    - msinttypes  # [win]
  run:
    - python
    - sdl2
    - sdl2_mixer
    - ffmpeg
    - libflac  # [win]
    - libvorbis  # [win]

test:
  imports:
    - ffpyplayer.player
  commands:
    - nosetests ffpyplayer/tests
    - python -c "import ffpyplayer"
  requires:
    - nose
  source_files:
    - examples
    - ffpyplayer/tests/test_pic.py
    - ffpyplayer/tests/test_write.py

about:
  home: https://github.com/matham/ffpyplayer
  license: LGPL-3.0
  license_family: LGPL
  license_file: COPYING
  summary: 'A cython implementation of ffmpeg based player, ffplay'

  description: |
    FFPyPlayer is a python binding for the FFmpeg library for playing and writing
    media files.
  doc_url: http://matham.github.io/ffpyplayer/index.html
  dev_url: https://github.com/matham/ffpyplayer

extra:
  recipe-maintainers:
    - matham
