travis:
  secure:
    BINSTAR_TOKEN: nLYPIGHhl/FNwFs1PnMaIIOppVWc38BibxJdqA4RLuRIO5bnaY+zueDlXou9TSR/Xrg4sXKafdWmYkzINd3tmM61KAjceF/w4QZG7nV7bYfY2gfUmx4ey1dOzwpVaG0mw6iYUx5VafbXzuRHY2UyvN3QkkuOo4yuANJ5VFQjg1CWuMmXR6s0Ut5LjDpaKsq9Yu5m2gyq4yrQ3uC6ejkBeCK7hCsMjsqDxyeRl2uRwIL5cNJqYomswRtW1ZVXG8x6JpbPBZOUqHYENQSD1JjbqxoMhJwWr6RJU6KPHtlJ9xVD5h4vQSTKQlNJNZ6hNYVER9+W0wSBVTZ//FikBFDj8n9eLGnqroAk75zGLsYGevhSKycnLP9zn0yW5uZ4eO4YI68J+WBlw2YqKKwKIxxbyopuemGWqEg4Cu1QapUE+uEp/LsnTgOVv6PxHjWT26hVILfu6cdaZtdTbOr8iDGab2ro25V7heK326duK6+nI8JP4cu33jG//e/NedtY85RxVW6Iu55fmE5nvpt3t1ZR7N4af3XtF2ImCJnQGNJTT+d1h9L9ofbxYSTDHbu/qVA9IzU0TI8m482Zkbu9gZ5owFSHnPb1yERkjJCwZLBKNzJYLX5rfS6hc2V99kD6elaIEbeWO/Kc9M1GZ38ttBzuS4hX6mKKtO0vT5fppiRpXSk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
