travis:
  secure:
    BINSTAR_TOKEN: NPbUuMRyv5WHROV4JgK+q/U6mQQ+c4/rxD+b4zy5qVwqasxsW6bEZRzZyQ/5/4fTVCSswf5jPY1rh+MnFLj9Ni+8P5PWXjrudcnDKvmO1L2F8hnoTaeApT0dppKIcLg/dNCMgqE87hE6cSUT8BB6m9a9LbX6hU0fkIVMBisiMzq3f4vD8Gw6icQGmBT4hUJnUN3bYSeruyssyFy5bwyAv0Y3IxFDp/xHZa1mVHT35KHU/SLHNt1EkAzmdPr86YyWUJcSfKGpwW0Q+4edHK1kTtogL8isydKj7+zA5Sbsfx3VX9Mc85c9K5Tpa07WvCigslCGmVltLqY8oKZsBP9nNkEbbx0OPqwQVZp1rMN3UOxEtdvru7tjSX7HU0dP2qsoXoH0S/fVt0IRjh3qfrFmtgKV8kpjXKn5v6Lw9pU7vg4nJbpt0ioZ0kNGgUfHZJuwdDWlkI7LZqEbRs9mdQRXomflFzVkGxjKPPkqbO7c7lcOM2x2qieSPJhw4WWE5kI+qd9BEGim4Mde7TsZh6GClcRwm7jm84SR44r+CFFXzrIcV1MT/eomA/ZtEFUt+xWtF0+5obrc+UhQ8zZ1bFJ3WAWavmFE9dc/FxcJDF9qOz8NWI/URF5amP3DZ2UnyJo1F/0UwN9Bf76EYKfJTjcF9BLlXmFP1U+rtOla37YDgqQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
